# Generated by Django 4.2 on 2024-08-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefiles',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
