# Generated by Django 4.2 on 2024-09-03 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mapa', '0007_alter_map_main_map_selected'),
        ('app_files', '0002_sourcefiles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefiles',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_mapa.map'),
        ),
    ]
