# Generated by Django 4.2 on 2024-08-06 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_fazenda', '0001_initial'),
        ('app_mapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_fazenda.farm'),
        ),
    ]
