# Generated by Django 4.2 on 2024-08-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fazenda', '0002_farm_created_at_farm_updated_at'),
        ('app_mapa', '0003_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='main_map_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='map',
            unique_together={('farm', 'main_map_selected')},
        ),
    ]
