# Generated by Django 4.2 on 2024-08-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mapa', '0004_map_main_map_selected_alter_map_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
