# Generated by Django 4.2 on 2024-08-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mapa', '0005_alter_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='long',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
