# Generated by Django 4.2 on 2024-08-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mapa', '0006_map_lat_map_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='main_map_selected',
            field=models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO')], default='nao', max_length=3),
        ),
    ]
